### ISSUE TITLE
Unable to set query params on api_auth.OIDCReadCallback on v0.2

### ISSUE THREAD

**Issue by pfremm** [hashicorp/vault-client-go#155]
# Expected Behavior

The callback on OIDCReadCallback to allow for setting query params to complete OIDC based auth to return a vault token.

# Current Behavior

Unable to validate a valid request as setting the query params on v0.2 of the SDK when looking at the code.
https://github.com/hashicorp/vault-client-go/blob/f439b5a9cefbc9a98cbebf7a6d8b9db06ed1fd3b/api_auth.go#L5102

I am not able to set query parameter to provide state, nonce, and code per the vault api doc:
https://developer.hashicorp.com/vault/api-docs/auth/jwt#oidc-callback

## Steps to Reproduce

1.Using the SDK call Auth.OIDCWriteAuthURL complete auth with identity provider
2. Attempt to leverage OIDCReadCallback to obtain a vault token

Is this SDK just not functionally complete at this point?

**Comment by averche** [comment]
Thanks for reporting the issue, @pfremm!

It appears that the `openapi.json` file used to generate the method in question (`OIDCReadCallback`) is not correct and does not have the required fields you listed. `GET` query parameters are quite rare in Vault (with notable exception of `list=true`), so I'm guessing we don't handle them well enough when generating the underlying `openapi.json` document. We will investigate the logic and see how it can be fixed.

In the meantime, you can manually form the request using `client.ReadWithParameters(...)` which accepts query parameters. 

> Is this SDK just not functionally complete at this point?

This library is currently in public beta. While it is fully functional, some bugs are expected and the API may change in non-backwards compatible ways. For production use-cases, please use the production-ready [vault/api](https://github.com/hashicorp/vault/tree/main/api) library.

**Comment by pfremm** [comment]
The production api doesn't implement this either.  Are you generating the openapi.json?  I see in the read me it states it's different than what vault provides.  Would you be open to a PR with the corrections?

**Comment by averche** [comment]
Yes, the `openapi.json` is generated dynamically using [gen_openapi.sh](https://github.com/hashicorp/vault/blob/main/scripts/gen_openapi.sh), which starts up a local vault, loads all built-in plugins (including `jwt` in this case) and calls [`sys/internal/specs/openapi`](https://developer.hashicorp.com/vault/api-docs/system/internal-specs-openapi) endpoint. The actual logic for generating the spec is in [openapi.go](https://github.com/hashicorp/vault/blob/main/sdk/framework/openapi.go).

Any contributions are super welcome, both in this library in vault!

>  I see in the read me it states it's different than what vault provides.

There is currently no official Vault openapi document, hence the warning in the README. We are working on polishing the openapi spec before officially releasing it.

**Comment by averche** [comment]
Hi @pfremm,

I've released a workaround for this issue in [v0.3.2](https://github.com/hashicorp/vault-client-go/releases/tag/v0.3.2). You can now do the following:

```go
	resp, err := client.Auth.JwtOidcCallback(
		ctx,
		vault.WithCustomQueryParameters(url.Values{
			"state": {"..."},
			"nonce": {"..."},
			"code":  {"..."},
		}),
	)
```

As mentioned before, ideally, we would like to support this at the OpenAPI schema level, but that might involve a lot more work on the schema generation side. Hopefully, this intermediate solution is sufficient for now.

**Comment by maxb** [comment]
I think the necessary fix here is to just set `Query: true` on these parameters. I have just created https://github.com/hashicorp/vault/pull/21949 which does a deep dive into the `Query` setting, improves its documentation, and adds it to various missing places within the Vault main repo. We should add it to this vault-plugin-auth-jwt endpoint as well.

**Comment by maxb** [comment]
hashicorp/vault-plugin-auth-jwt#246 should address this.

Do we want `WithCustomQueryParameters` to exist in the library long term? It seems like something people shouldn't need, outside of workarounds.

**Comment by averche** [comment]
This is awesome, thanks again @maxb! I'll try to take a look and approve your PR's tomorrow :)

> Do we want WithCustomQueryParameters to exist in the library long term? It seems like something people shouldn't need, outside of workarounds.

We may still want these for the generic Read/Write/Delete methods. One option would be to revert https://github.com/hashicorp/vault-client-go/pull/189.

**Comment by maxb** [comment]
> I'll try to take a look and approve your PR's tomorrow :)

Thanks :-)   For today, and next week, I have loads of free time, in case you want to pull me in to a Zoom call to ask questions.   After that, I start a new job, and my hobbyist coding time will be much reduced.

**Comment by maxb** [comment]
> > Do we want WithCustomQueryParameters to exist in the library long term? It seems like something people shouldn't need, outside of workarounds.
> 
> We may still want these for the generic Read/Write/Delete methods. One option would be to revert #189.

I think that restoring the `ReadWithParameters`, `ReadRawWithParameters`, `DeleteWithParameters` functions, and maybe adding a new `ListWithParameters`, could be a good approach as it makes specifying arbitrary query parameters more discoverable for the few APIs that actually should need it, whilst removing some complexity from the rest of the APIs.

Note: no need for `WriteWithParameters`, as Vault does not support use of query-params with PUT/POST methods.

**Comment by maxb** [comment]
Thanks for the multiple PR approvals and merges today. Just to chart out the next steps:

* https://github.com/hashicorp/vault/pull/21942 is required so that the newly configured `Query: true` metadata has the correct effect
* We need to pull the updated plugin into the Vault main repo, e.g. https://github.com/hashicorp/vault/pull/22023
* There are two previous "Sync OpenAPI" PRs that'll need to be merged - #202 #203 - before we can sync the `Query` related changes into this repo

**Comment by maxb** [comment]
A change is now incoming in #211 that will change the method parameters to:
```
JwtOidcCallback(ctx context.Context, clientNonce string, code string, state string, options ...RequestOption)
```

**Comment by maxb** [comment]
Lastly, #213 is needed to fix another bug. With that, I have successfully tested an OIDC login using this function.



> I think that restoring the `ReadWithParameters`, `ReadRawWithParameters`, `DeleteWithParameters` functions, and maybe adding a new `ListWithParameters`, could be a good approach as it makes specifying arbitrary query parameters more discoverable for the few APIs that actually should need it, whilst removing some complexity from the rest of the APIs.

I considered PRing this, but it turns out to be a **lot** of moving code around for a very niche feature... an alternative could be to just drop the word `Custom` from `WithCustomQueryParameters` (since it doesn't make sense in the long-term intended usage situation of the plain Read/ReadRaw/List/Delete methods), and to expand the docstring to state those are the only methods it is recommended for use with.

**Comment by averche** [comment]
> I considered PRing this, but it turns out to be a **lot** of moving code around for a very niche feature... an alternative could be to just drop the word `Custom` from `WithCustomQueryParameters` (since it doesn't make sense in the long-term intended usage situation of the plain Read/ReadRaw/List/Delete methods), and to expand the docstring to state those are the only methods it is recommended for use with.

That's not a bad idea, I like it :)

**Comment by averche** [comment]
I believe we can close this ticket now. I will release this as part of 0.4.0 next week. Thanks a lot of solving the issue @maxb!
