### ISSUE TITLE
Please upload documentation to pkg.go.dev

### ISSUE THREAD

**Issue by MushiTheMoshi** [hashicorp/vault-client-go#157]
## Describe the feature request or question
in golang normally docs are in pkg.go.dev, can you please follow this standard is easy to read and all gophers will be able to read accordingly 

## A clear and concise description of what the problem is. 
if I want to search for a type or any other object I have to dive into the code, will be pretty much faster (and standardized) using pkg documentation

**Comment by averche** [comment]
Hi @MushiTheMoshi!

The documentation for this library can be found at https://pkg.go.dev/github.com/hashicorp/vault-client-go. Is there something else you had in mind?

**Comment by MushiTheMoshi** [comment]
I swear I looked for it hahaha, sorry for wasting your valuable time. Can you add it in the README?

**Comment by averche** [comment]
No worries at all 😃 The documentation is currently linked in the README as [![Go Reference][go-reference-badge]][go-reference] badge at the top. We could add it somewhere as a text link as well. Thanks for the feedback! 

[go-reference-badge]:    https://pkg.go.dev/badge/github.com/hashicorp/vault-client-go
[go-reference]:          https://pkg.go.dev/github.com/hashicorp/vault-client-go
