### ISSUE TITLE
Auth.AwsWriteAuthRole usage documentation incorrect

### ISSUE THREAD

**Issue by MushiTheMoshi** [hashicorp/vault-client-go#167]
# Expected Behavior
I can read auth/aws/role/ROLE like vault read auth/aws/role/ROLE

# Current Behavior
Types from the documentation are not matching

# Failure Information
```.go
	role := "ROLE"
	request := schema.NewAwsWriteAuthRoleRequestWithDefaults()
	resp2, err := client.Auth.AwsWriteAuthRole(
		context.Background(),
		role,
		request,
		vault.WithToken(resp.Auth.ClientToken),
		vault.WithMountPath("aws"),
	)
	if err != nil {
		log.Fatal(err)
	}
```

Please include the version of Vault binary and the version of `vault-client-go` you're using.
github.com/hashicorp/vault-client-go v0.3.0

Error:
```
cannot use request (variable of type *schema.AwsWriteAuthRoleRequest) as type schema.AwsWriteAuthRoleRequest in argument to client.Auth.AwsWriteAuthRole
```

Hope you can help me.

Regards,
Julio

**Comment by MushiTheMoshi** [comment]
additionally I am reading this piece of doc: https://github.com/hashicorp/vault-client-go/blob/main/docs/AuthApi.md#awswriteauthrole

**Comment by averche** [comment]
Hi @MushiTheMoshi,

The generated docs are not quite correct here. Currently the request is passed by value. We are considering changing that in the future versions. The current syntax is:

```go
resp2, err := client.Auth.AwsWriteAuthRole(
		context.Background(),
		role,
		*request,
		vault.WithToken(resp.Auth.ClientToken),
		vault.WithMountPath("aws"),
)
```

Alternatively:

```go
resp2, err := client.Auth.AwsWriteAuthRole(
		context.Background(),
		role,
		AwsWriteRoleRequest{
		      // populate request parameters
		},
		vault.WithToken(resp.Auth.ClientToken),
		vault.WithMountPath("aws"),
)
```
