### ISSUE TITLE
client.Identity.MfaConfigureTotpMethod and similar do not work to create new MFA methods

### ISSUE THREAD

**Issue by maxb** [hashicorp/vault-client-go#180]
# Expected Behavior

Creation of MFA methods is possible using the library.

# Current Behavior

There is no obvious way to invoke the MFA method creation APIs, like `identity/mfa/method/totp`.

If `client.Identity.MfaConfigureTotpMethod` is invoked passing an empty string as the method_id, Vault returns an error message: `400: cannot write to a path ending in '/'`

# Failure Information

Vault 1.13.2 (latest release)
vault-client-go current main

## Steps to Reproduce

Run this code
```
    _, err = client.Identity.MfaConfigureTotpMethod(ctx, "", schema.MfaConfigureTotpMethodRequest{
        Issuer: "foobar",
    })
    if err != nil {
        log.Fatal(err)
    }
```

# Additional Information

This bug is not located in the library at all - the fault is in Vault core. The correct endpoint is never generated into the OpenAPI spec at all, because of the path collides with the path calculated for the LIST operation, and the relevant key in a map gets overwritten.

I'm planning to open a PR against Vault in the next few days and will link this issue.

**Comment by averche** [comment]
Thanks again, @maxb!

This seems like a similar issue to #174. Looking forward to your PR against Vault!

**Comment by maxb** [comment]
> I'm planning to open a PR against Vault in the next few days and will link this issue.

These are now ready:

* hashicorp/vault#20879 to fix the issue
* hashicorp/vault#20873 to add logging, to make it more likely that a recurrence of a similar issue would be spotted
