### ISSUE TITLE
Reading deleted secrets failed due to 404 response from Vault

### ISSUE THREAD

**Issue by Adrianos712** [hashicorp/vault-client-go#246]
# Expected Behavior

Being able to read KVv2 deleted secrets or to know if the returned code 404 is an error or not

# Current Behavior

When reading a KVv2 deleted secret, Vault API returns HTTP code 404 but with the secret in the JSON body like this:
```json
{
  "request_id": "657ccf81-56a7-453e-6332-7fcc26b2ee93",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "data": null,
    "metadata": {
      "created_time": "2023-11-30T15:54:25.800266627Z",
      "custom_metadata": null,
      "deletion_time": "2023-12-06T17:20:38.209728575Z",
      "destroyed": false,
      "version": 1
    }
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}

```

function `isResponseError()` does not handle it well:

```
	// try to decode as a list of errors
	var jsonResponseErrors struct {
		Errors []string `json:"errors"`
	}
	if err := json.Unmarshal(responseBody, &jsonResponseErrors); err == nil {
		responseError.Errors = jsonResponseErrors.Errors
		return responseError // early return
	}
```
here we have a response body with valid JSON not containing an `errors` key but the function returns nil

# Failure Information

Vault: 1.10.0
vault-client-go: v0.4.2

## Steps to Reproduce

1. Auth with Vault
2. Use KvV2Read() on a deleted secret
3. See the return of the function: *vaultClient.Response == nil, err != nil
err.Errors() == nil
err.StatusCode == 404 but not accessible?
...

**Comment by averche** [comment]
Hi @Adrianos712,

The 404 JSON response returned by KVv2Read is a non-standard error response for Vault but we should definitely handle it better. Thanks for catching this issue!

I'm working on a solution to return the raw response body as part of the error struct.
