### ISSUE TITLE
package not in GOROOT

### ISSUE THREAD

**Issue by andyfen** [hashicorp/vault-client-go#256]
it's most probably me, but when i run

` go get -u github.com/hashicorp/vault-client-go`

i see 
```
github.com/hashicorp/vault-client-go imports
	maps: package maps is not in GOROOT (/usr/local/go/src/maps)
github.com/hashicorp/vault-client-go imports
	slices: package slices is not in GOROOT (/usr/local/go/src/slices)
```
any ideas ? thanks

**Comment by averche** [comment]
Hi @andyfen,

I believe `slices` and `maps` packages require go 1.21 or higher. Could you please check which version of Go you are using for your project & tooling?
